### ISSUE TITLE
Exception uploading word document

### ISSUE THREAD

**Issue by siparsons** [pbearne/Bullhorn2WP#18]
I get the following issue while attempting to upload CV's using the plugin

```Fatal error: Uncaught exception 'Exception' with message 'There was a problem logging into the Bullhorn API.' in /home/morganhealey/public_html/wp-content/plugins/bh-staffing-job-listing-and-cv-upload-for-wp/bullhorn.php:67 Stack trace: #0 /home/morganhealey/public_html/wp-content/plugins/bh-staffing-job-listing-and-cv-upload-for-wp/cron.php(40): Bullhorn_Connection::sync() #1 [internal function]: bullhorn_sync_now('') #2 /home/morganhealey/public_html/wp-includes/class-wp-hook.php(298): call_user_func_array('bullhorn_sync_n...', Array) #3 /home/morganhealey/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #4 /home/morganhealey/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /home/morganhealey/public_html/wp-admin/admin.php(154): do_action('admin_init') #6 /home/morganhealey/public_html/wp-admin/options-general.php(10): require_once('/home/morganhea...') #7 {main} thrown in /home/morganhealey/public_html/wp-content/plugins/bh-staffing-job-listing-and-cv-upload-for-wp/bullhorn.php on line 67```

**Comment by pbearne** [comment]
Hi 

The API tokens needs to be refreshed in the admin. But that  is not a long term fix as it will happen again. 

We have new version of the plugin that we have rewritten from the ground up that we are releasing as a beta version that solves this problem.

reach out to me at paul@bearne.ca and lets have chat you joining the beta programe

Paul
